### ISSUE TITLE
ping_devs function cannot notify devs when error message is too long

### ISSUE THREAD

**Issue by Ahsoka** [ryanlee68/bdaybot#10]
### What is the [`ping_devs`] function?
[`ping_devs`] is a function in [`utils.py`](https://github.com/Ahsoka/bdaybot/blob/master/bdaybot/utils.py) that allows the bot to send the developers of the bot a message whenever something goes with the bot with a detailed error log.
### The Issue
Sometimes the error message is so long that it does not fit within the 2000 character limit that all Discord messages must be under.  When the bot attempts to send an error message with more than 2000 characters this causes an error in the [`ping_devs`] function.  This is a major issue with the bot as errors may go undetected if [`ping_devs`] fails to send the developers of the bot an error message.  This should ideally be fixed as soon as possible to prevent any errors from going undetected.  Generally speaking, SQLAlchemy errors tend to be the errors that cause this issue (since they are really long).

[`ping_devs`]: https://github.com/Ahsoka/bdaybot/blob/master/bdaybot/utils.py#L110

**Comment by Russian1895** [comment]
we are doomed
