### ISSUE TITLE
Add Discord's new Feature: Slash Commands

### ISSUE THREAD

**Issue by ryanlee68** [ryanlee68/bdaybot#27]
What?
Slash command are Discord's new custom built implementation of commands, see the image for an example:
![Sample of Slash Commands](https://cdn.discordapp.com/attachments/826726633888546856/831234563899392020/slash.JPG) 

Why?
This is now more of a priority since discord is in the process of making it harder to utilize the message content intent, which is what text based commands rely on in order to function.  Additionally, the current version of `discord.py` we are using (which is 1.7.3) is set to no longer work near the start of 2023, see [here](https://github.com/discord/discord-api-docs/discussions/4725) for reference.  Since we are now transitioning to Pycord it make sense to implement slash command since it is not that difficult.

When?
This transition should be done before API v7 decommissioning, which as mentioned above is near the start of the 2023.

How?
Transition the following commands to slash commands, this transition will occur on the [`slash-commands` branch](https://github.com/Ahsoka/bdaybot/tree/slash-commands) until it is stable enough to be put on the [`master` branch](https://github.com/Ahsoka/bdaybot/tree/master).
* [x] Wish (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/90fd002393dde7f6fdbe28e91846087c969cbdbd)
* [x] Get ID (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/51148e1f08f9019f00f5a0ab04edb8d21021d1f8)
* [x] Set ID (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/865903206241a03a9229beeeecbda48fb018b0b3)
* [x] Upcoming (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/ed2290e0bf4785e41c6496089ce926e210b5dc31)
* [x] Set announcements (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/baaddacb3cdc61460c531e69e8f922206e2b28aa)
* [x] Get announcements (completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/90dfcc3ca6220fde6f77fe646e8b90030b9ccc32)
* [x] Get wishes (formally just called wishes, completed by @Ahsoka, see https://github.com/Ahsoka/bdaybot/commit/020c648b86f6f3624c6143cb3b559a20d48640d2)
* [x] #35

**Comment by ryanlee68** [comment]
@Ahsoka :discord.py will be adding support for them in version 2.0 so idk if you want to wait around for that or just implement them now with the third-party library

Reference: https://github.com/Rapptz/discord.py/issues/6149

**Comment by Ahsoka** [comment]
Will implement once https://github.com/Rapptz/discord.py/issues/6149 is closed

**Comment by Ahsoka** [comment]
Update on this issue, discord.py is no longer being developed, if you want to implement slash commands use this library: https://github.com/goverfl0w/discord-interactions

**Comment by Ahsoka** [comment]
I would recommend actually using [Pycord](https://github.com/Pycord-Development/pycord) instead of [discord-interactions](https://github.com/goverfl0w/discord-interactions).  Discord-interactions is still a very young library and lacks a lot of features.  Pycord is a fork of Discord.py and should be relatively easy to integrate with current bdaybot code.  However, keep in mind at the writing of this post Pycord's implementation of slash commands is still in beta and it may be worth waiting until a stable version of Pycord is released.
